/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo.index'
import { Route as CatalogoCategoriaRouteImport } from './routes/catalogo.$categoria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogoRoute,
} as any)
const CatalogoCategoriaRoute = CatalogoCategoriaRouteImport.update({
  id: '/$categoria',
  path: '/$categoria',
  getParentRoute: () => CatalogoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/catalogo/$categoria': typeof CatalogoCategoriaRoute
  '/catalogo/': typeof CatalogoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo/$categoria': typeof CatalogoCategoriaRoute
  '/catalogo': typeof CatalogoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/catalogo/$categoria': typeof CatalogoCategoriaRoute
  '/catalogo/': typeof CatalogoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalogo' | '/catalogo/$categoria' | '/catalogo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogo/$categoria' | '/catalogo'
  id: '__root__' | '/' | '/catalogo' | '/catalogo/$categoria' | '/catalogo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof CatalogoRoute
    }
    '/catalogo/$categoria': {
      id: '/catalogo/$categoria'
      path: '/$categoria'
      fullPath: '/catalogo/$categoria'
      preLoaderRoute: typeof CatalogoCategoriaRouteImport
      parentRoute: typeof CatalogoRoute
    }
  }
}

interface CatalogoRouteChildren {
  CatalogoCategoriaRoute: typeof CatalogoCategoriaRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoCategoriaRoute: CatalogoCategoriaRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
